fix: dependencies were not working

diff --git a/Shakefile b/Shakefile
--- a/Shakefile
+++ b/Shakefile
@@ -1,25 +1,7 @@
-main: say
-	echo "hello"
-list:
-	ls .
-	if [ 1 ];then
-		echo "dev"
-	fi
-way: list main go
-	:
-go: main list way
-	for i in `seq 3`
-	do
-		echo ${i}
-	done
-say:
-	say "hello"
-circ: circ
-	say "circular"
-build:
+build: go
 	go build shake.go
 version:
-	echo "v0.0.1-alpha"
+	echo "v0.0.1-alpha2"
 tag:
 	TAG=${RELEASE_TAG:-$(./shake version)}
 	if [ -z ${TAG} ];then
@@ -27,7 +9,32 @@ tag:
 		exit 1
 	fi
 	git tag ${TAG} | true
-release: build
+go:
+	if [ -z `which go` ];then
+		echo "can't go..."
+		exit 1
+	fi
+goreleaser: go
+	go get github.com/goreleaser/goreleaser
+release: build goreleaser
 	GITHUB_TOKEN=$(./shake decrypt) goreleaser --rm-dist
 decrypt:
 	openssl aes-256-cbc -d -in github_token.enc
+hello: say
+	echo "hello"
+list:
+	ls .
+	if [ 1 ];then
+		echo "dev"
+	fi
+way: list hello go
+	:
+seq: hello list way
+	for i in `seq 3`
+	do
+		echo ${i}
+	done
+say:
+	say "hello"
+circ: circ
+	:
